pipeline {
    agent any
    stages {
        stage('Pre-check Docker') {
            steps {
                sh 'docker --version'
                sh 'docker info > /dev/null'
                echo 'Docker is available and running'
            }
        }
        stage('Cleanup Old Containers') {
            steps {
                sh 'docker rm -f delivery_metrics prometheus grafana || true'
            }
        }
        stage('Setup Workspace') {
            steps {
                sh '''
                cp /project/delivery_metrics.py $WORKSPACE/
                cp /project/prometheus.yml $WORKSPACE/
                cp /project/alert_rules.yml $WORKSPACE/
                cp /project/Dockerfile $WORKSPACE/
                '''
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t delivery_metrics .'
            }
        }
        stage('Run Application') {
            steps {
                sh 'docker run -d -p 8000:8000 --name delivery_metrics delivery_metrics'
            }
        }
        stage('Run Prometheus & Grafana') {
            steps {
                sh '''
                docker create --name prometheus -p 9090:9090 --add-host=host.docker.internal:host-gateway prom/prometheus
                docker cp prometheus.yml prometheus:/etc/prometheus/prometheus.yml
                docker cp alert_rules.yml prometheus:/etc/prometheus/alert_rules.yml
                docker start prometheus
                docker run -d --name grafana -p 3000:3000 --add-host=host.docker.internal:host-gateway grafana/grafana
                '''
            }
        }
    }
}
